name: Deploy GitHub Pages (monorepo)

on:
  push:
    branches: [ main ]
    paths:
      - "2d-game/**"
      - "apple-game/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build 2d-game
        run: pnpm --filter 2d-game build

      - name: Build apple-game
        run: pnpm --filter apple-game build

      - name: Prepare Pages artifact structure
        run: |
          set -eux
          mkdir -p ./pages-out/2d-game
          mkdir -p ./pages-out/apple-game
          # Copy Vite build outputs; adjust if outDir differs
          if [ -d "2d-game/dist" ]; then cp -R 2d-game/dist/* ./pages-out/2d-game/; fi
          if [ -d "apple-game/dist" ]; then cp -R apple-game/dist/* ./pages-out/apple-game/; fi
          # Add a simple index to link both apps
          cat > ./pages-out/index.html <<'HTML'
          <!doctype html>
          <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>Monorepo Apps</title>
              <style>
                body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif; margin: 40px; }
                h1 { margin-bottom: 16px; }
                ul { line-height: 1.9; }
                a { color: #2563eb; text-decoration: none; }
                a:hover { text-decoration: underline; }
              </style>
            </head>
            <body>
              <h1>Monorepo Apps</h1>
              <ul>
                <li><a href="./2d-game/">2d-game</a></li>
                <li><a href="./apple-game/">apple-game</a></li>
              </ul>
            </body>
          </html>
          HTML

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./pages-out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4